name: Publish Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: sersoft-gmbh/swifty-docs-action@v3
      with:
        output: docs
        xcodebuild-scheme: CoreExtensions


