# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Unit Tests (iOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_15.1.app
    - name: Run Tests
      run: set -o pipefail && xcodebuild test -scheme SwiftExtensions-Package -sdk iphonesimulator -destination "OS=17.2,name=iPhone 15" | xcbeautify
